version: '3.8'

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    container_name: celery_worker
    command: celery --app app.config.celery_config.celery_app worker --loglevel=info --pool=solo
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
