version: '3.8'

services:
  webapi:
    restart: always
    build: .
    container_name: call_analyzer
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./data:/code/data
      - ./mp3:/code/mp3
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    restart: always
    container_name: celery_worker
    volumes:
      - ./data:/code/data
      - ./mp3:/code/mp3
    command: celery --app app.config.celery_config.celery_app worker --loglevel=info --pool=solo
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower
    ports:
      - "5555:5555"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

  redis:
    image: redis/redis-stack:latest
    container_name: redis_server
    ports:
      - "6379:6379"
      - "8001:8001"
