name: Build, Tag and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }} /${{ secrets.DOCKERHUB_REPO_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Docker Login to First Account
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and Push Docker Image to First Account
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Docker Login to Second Account
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SECOND_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SECOND_DOCKERHUB_TOKEN }}
          logout: true

      - name: Tag Image for Second Repository
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:${{ steps.meta.outputs.version }} ${{ secrets.SECOND_DOCKERHUB_USERNAME }}/${{ secrets.SECOND_DOCKERHUB_REPO_NAME }}:${{ steps.meta.outputs.version }}

      - name: Push Docker Image to Second Account
        run: |
          docker push ${{ secrets.SECOND_DOCKERHUB_USERNAME }}/${{ secrets.SECOND_DOCKERHUB_REPO_NAME }}:${{ steps.meta.outputs.version }}
