name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ROOT }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy to EC2
        env:
          PEM_FILE: ${{ secrets.EC2_SSH_PRIVATE_KEY_PEM }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          
          echo "Setting up SSH key"
          echo "$PEM_FILE" > private_key.pem
          chmod 600 private_key.pem
          echo "SSH key setup completed"

          echo "Testing SSH connection"
          ssh -v -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -i private_key.pem ${USER}@${HOST} 'echo "SSH connection successful"' || { echo "SSH connection failed"; exit 1; }
          echo "SSH connection test completed"

          echo "Starting deployment"
          ssh -v -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -i private_key.pem ${USER}@${HOST} <<'EOF'
            set -e

            echo "Navigating to project directory"
            cd ICSMS-Call-Analyzer-Backend || { echo "Directory not found"; exit 1; }

            echo "Pulling latest changes from Git"
            git pull origin master || { echo "Git pull failed"; exit 1; }

            echo "Stopping existing Docker containers"
            docker-compose down || { echo "Docker-compose down failed"; exit 1; }

            echo "Building Docker containers"
            docker-compose build || { echo "Docker-compose build failed"; exit 1; }

            echo "Starting Docker containers"
            docker-compose up -d || { echo "Docker-compose up failed"; exit 1; }

            echo "Checking Docker container status"
            docker-compose ps || { echo "Docker-compose ps failed"; exit 1; }

            echo "Displaying Docker logs"
            docker-compose logs -f
          EOF || { echo "Deployment failed"; exit 1; }
