name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ROOT }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy to EC2
        env:
          PEM_FILE: ${{ secrets.EC2_SSH_PRIVATE_KEY_PEM }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PEM_FILE" > private_key.pem && chmod 600 private_key.pem
          echo "Trying to SSH into ${HOST} with user ${USER}"
          ssh -v -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} 'echo "SSH connection successful"'
          echo "SSH connection test completed"
          
          ssh -v -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} '
            echo "Current directory: $(pwd)"
            ls -al
            cd ICSMS-Call-Analyzer-Backend/ &&
            echo "Changed directory to ICSMS-Call-Analyzer-Backend"
            git pull origin master &&
            echo "Git pull completed"
            docker-compose down &&
            echo "Docker Compose down completed"
            docker-compose build &&
            echo "Docker Compose build completed"
            docker-compose up -d &&
            echo "Docker Compose up completed"
          ' || { echo "SSH command failed"; exit 1; }
